apiVersion: apps/v1
kind: Deployment
metadata:
  name: rubik-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rubik-server
  template:
    metadata:
      labels:
        app: rubik-server
    spec:
      containers:
        - name: rubik-server-container
          image: rubik-server:v1
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
